version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn djangoPKI.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 8000
    env_file:
      - ./.env.prod

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - 443:443
    depends_on:
      - web