version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn djangoPKI.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 8000
    volumes:
      - static_volume:/home/app/web/staticfiles
    env_file:
      - ./.env.prod

  nginx:
    restart: unless-stopped
    image: staticfloat/nginx-certbot
    ports:
      - 80:80/tcp
      - 443:443/tcp
    environment:
      CERTBOT_EMAIL: david.tillemans@cryptable.org
    volumes:
      - ./conf.d:/etc/nginx/user.conf.d:ro
      - letsencrypt:/etc/letsencrypt
      - static_volume:/home/app/web/staticfiles
    depends_on:
      - web

volumes:
  letsencrypt:
  static_volume: