# Generated by Django 3.1 on 2020-08-15 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number_text', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='PrivateKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password_text', models.CharField(max_length=64)),
                ('private_key_text', models.CharField(max_length=10240)),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name_text', models.CharField(max_length=64)),
                ('given_name_text', models.CharField(max_length=16, null=True)),
                ('sur_name_text', models.CharField(max_length=40, null=True)),
                ('initials_text', models.CharField(max_length=5, null=True)),
                ('pseudonym_text', models.CharField(max_length=128, null=True)),
                ('generation_qualifier_text', models.CharField(max_length=3, null=True)),
                ('title_text', models.CharField(max_length=128, null=True)),
                ('locality_name_text', models.CharField(max_length=128, null=True)),
                ('state_name_text', models.CharField(max_length=128, null=True)),
                ('organization_name_text', models.CharField(max_length=64, null=True)),
                ('organizational_unit_name_text', models.CharField(max_length=128, null=True)),
                ('postal_code_text', models.CharField(max_length=16, null=True)),
                ('country_code_text', models.CharField(max_length=2, null=True)),
                ('subject_text', models.CharField(max_length=8192)),
                ('issuer_text', models.CharField(max_length=8192)),
                ('serial_number_text', models.CharField(max_length=128)),
                ('certificate_text', models.CharField(max_length=10240)),
                ('ca', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='ca.ca')),
                ('private_key', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ca.privatekey')),
            ],
        ),
    ]
