# Generated by Django 3.1 on 2020-08-16 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ca', '0003_auto_20200815_1806'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ca',
            old_name='serial_number_text',
            new_name='crl_number_text',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='initials_text',
        ),
        migrations.AddField(
            model_name='certificate',
            name='domain_component_1_text',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='domain_component_2_text',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='domain_component_3_text',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='domain_component_4_text',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='domain_component_5_text',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='email_address_text',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='street_name_text',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='subject_serial_number_text',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
