# Generated by Django 3.1 on 2020-10-18 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ca', '0004_auto_20200816_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='domain_component_1_text',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='domain_component_2_text',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='domain_component_3_text',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='domain_component_4_text',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='domain_component_5_text',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
